service: prueba-tecnica

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
functions:
  getCharacters:
    handler: src/handlers/get-characters-handler.handler
    events:
      - http:
          path: api/characters
          method: get
  createCharacter:
    handler: src/handlers/create-character-handler.handler
    events:
      - http:
          path: api/character/{id}
          method: post
plugins:
  - serverless-offline